set role 'role_full_admin';

create table cprd_jun24nondm_data.ons_death engine=MyISAM as select * from cprd_jun24nondm_analysis.ons_death_final;
create index x_ons_death_pracid on cprd_jun24nondm_data.ons_death (pracid);
create index x_ons_death_reg_date_of_death on cprd_jun24nondm_data.ons_death (reg_date_of_death);
create index x_ons_death_pod_cod_1 on cprd_jun24nondm_data.ons_death (pod_cod_1);
create index x_ons_death_pod_cod_2 on cprd_jun24nondm_data.ons_death (pod_cod_2);
create index x_ons_death_pod_establishment_type_1 on cprd_jun24nondm_data.ons_death (pod_establishment_type_1);
create index x_ons_death_pod_establishment_type_2 on cprd_jun24nondm_data.ons_death (pod_establishment_type_2);
create index x_ons_death_nhs_indicator_1 on cprd_jun24nondm_data.ons_death (nhs_indicator_1);
create index x_ons_death_nhs_indicator_2 on cprd_jun24nondm_data.ons_death (nhs_indicator_2);
create index x_ons_death_cause_icd9_1 on cprd_jun24nondm_data.ons_death (cause_icd9_1);
create index x_ons_death_cause_icd9_2 on cprd_jun24nondm_data.ons_death (cause_icd9_2);
create index x_ons_death_cause_icd9_3 on cprd_jun24nondm_data.ons_death (cause_icd9_3);
create index x_ons_death_cause_icd9_4 on cprd_jun24nondm_data.ons_death (cause_icd9_4);
create index x_ons_death_cause_icd9_5 on cprd_jun24nondm_data.ons_death (cause_icd9_5);
create index x_ons_death_cause_1 on cprd_jun24nondm_data.ons_death (cause_1);
create index x_ons_death_cause_2 on cprd_jun24nondm_data.ons_death (cause_2);
create index x_ons_death_cause_3 on cprd_jun24nondm_data.ons_death (cause_3);
create index x_ons_death_cause_4 on cprd_jun24nondm_data.ons_death (cause_4);
create index x_ons_death_cause_5 on cprd_jun24nondm_data.ons_death (cause_5);
create index x_ons_death_cause_6 on cprd_jun24nondm_data.ons_death (cause_6);
create index x_ons_death_cause_7 on cprd_jun24nondm_data.ons_death (cause_7);
create index x_ons_death_cause_8 on cprd_jun24nondm_data.ons_death (cause_8);
create index x_ons_death_cause_9 on cprd_jun24nondm_data.ons_death (cause_9);
create index x_ons_death_cause_10 on cprd_jun24nondm_data.ons_death (cause_10);
create index x_ons_death_cause_11 on cprd_jun24nondm_data.ons_death (cause_11);
create index x_ons_death_cause_12 on cprd_jun24nondm_data.ons_death (cause_12);
create index x_ons_death_cause_13 on cprd_jun24nondm_data.ons_death (cause_13);
create index x_ons_death_cause_14 on cprd_jun24nondm_data.ons_death (cause_14);
create index x_ons_death_cause_15 on cprd_jun24nondm_data.ons_death (cause_15);
create index x_ons_death_cause_16 on cprd_jun24nondm_data.ons_death (cause_16);
create index x_ons_death_cause_17 on cprd_jun24nondm_data.ons_death (cause_17);
create index x_ons_death_underlying_cause_icd9_1 on cprd_jun24nondm_data.ons_death (underlying_cause_icd9_1);
create index x_ons_death_underlying_cause_1 on cprd_jun24nondm_data.ons_death (underlying_cause_1);
create index x_ons_death_underlying_cause_2 on cprd_jun24nondm_data.ons_death (underlying_cause_2);
create index x_ons_death_underlying_cause_3 on cprd_jun24nondm_data.ons_death (underlying_cause_3);
